version: "3"

services:
  spark:
    build:
      context: ./
    environment:
      - PYSPARK_MAJOR_PYTHON_VERSION=3
    volumes:
      - spark_data:/lab/

volumes:
  spark_data:
    name: spark_data
