version: "3.5"
services:
  node:
    container_name: lite-server
    build:
      context: .
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - lite_data:/node/app/src

volumes:
  lite_data:
    name: lite_data