version: "3.5"
services:
  node:
    container_name: json-server
    build:
      context: ./
    ports:
      - 3000:3000
    volumes:
      - json_data:/node/app/data

volumes:
  json_data:
    name: json_data
