version: '3'
services:

## Router
  router:
    image: mongo:6.0.1
    container_name: router-01
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    ports:
      - 27117:27017
    restart: always
    volumes:
      - ./scripts:/scripts
      - router_db:/data/db
      - router_config:/data/configdb

## Config Servers
  configsvr01:
    image: mongo:6.0.1
    container_name: mongo-config-01 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts 
      - configsvr01_db:/data/db
      - configsvr01_config:/data/configdb
    ports:
      - 27119:27017
    restart: always

  configsvr02:
    image: mongo:6.0.1
    container_name: mongo-config-02 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
      - configsvr02_db:/data/db
      - configsvr02_config:/data/configdb
    ports:
      - 27120:27017
    restart: always

  configsvr03:
    image: mongo:6.0.1
    container_name: mongo-config-03 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
      - configsvr03_db:/data/db
      - configsvr03_config:/data/configdb
    ports:
      - 27121:27017
    restart: always

## Shards
  ## Shards 01
   
  shard01-a:
    image: mongo:6.0.1
    container_name: shard-01-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
      - shard01_a_db:/data/db
      - shard01_a_config:/data/configdb
    ports:
      - 27122:27017
    restart: always

  shard01-b:
    image: mongo:6.0.1
    container_name: shard-01-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
      - shard01_b_db:/data/db
      - shard01_b_config:/data/configdb
    ports:
      - 27123:27017
    restart: always

  shard01-c:
    image: mongo:6.0.1
    container_name: shard-01-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
      - shard01_c_db:/data/db
      - shard01_c_config:/data/configdb
    ports:
      - 27124:27017
    restart: always

  ## Shards 02
  shard02-a:
    image: mongo:6.0.1
    container_name: shard-02-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - shard02_a_db:/data/db
      - shard02_a_config:/data/configdb
    ports:
      - 27125:27017
    restart: always

  shard02-b:
    image: mongo:6.0.1
    container_name: shard-02-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - shard02_b_db:/data/db
      - shard02_b_config:/data/configdb
    ports:
      - 27126:27017
    restart: always

  shard02-c:
    image: mongo:6.0.1
    container_name: shard-02-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - shard02_c_db:/data/db
      - shard02_c_config:/data/configdb
    ports:
      - 27127:27017
    restart: always

  ## Shards 03
  shard03-a:
    image: mongo:6.0.1
    container_name: shard-03-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
      - shard03_a_db:/data/db
      - shard03_a_config:/data/configdb
    ports:
      - 27128:27017
    restart: always

  shard03-b:
    image: mongo:6.0.1
    container_name: shard-03-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
      - shard03_b_db:/data/db
      - shard03_b_config:/data/configdb
    ports:
      - 27129:27017
    restart: always

  shard03-c:
    image: mongo:6.0.1
    container_name: shard-03-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
      - shard03_c_db:/data/db
      - shard03_c_config:/data/configdb
    ports:
      - 27130:27017
    restart: always

volumes:
  router_db:
  router_config:
  
  configsvr01_db:
  configsvr01_config:
  
  configsvr02_db:
  configsvr02_config:
  
  configsvr03_db:
  configsvr03_config:
  
  shard01_a_db:
  shard01_a_config:
  
  shard01_b_db:
  shard01_b_config:
  
  shard01_c_db:
  shard01_c_config:
  
  shard02_a_db:
  shard02_a_config:
  
  shard02_b_db:
  shard02_b_config:
  
  shard02_c_db:
  shard02_c_config:
  
  shard03_a_db:
  shard03_a_config:
  
  shard03_b_db:
  shard03_b_config:
  
  shard03_c_db:
  shard03_c_config: